name: Unit Tests
on:
  push:
    branch: main

jobs:
  unit-tests-gcc:
    name: Unit tests w/ g++
    runs-on: ubuntu-latest
    container: debian:bullseye-slim
    steps:
      - name: update apt + install CMake and g++
        run: apt-get update -q && apt-get install -y cmake g++ git
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Let CMake configure repo
        run: cmake -S . -B build/
      - name: Build Repo
        run: cmake --build build/
      - name: Run Unit Tests
        run: cd build/tests && ctest
  unit-tests-clang:
    name: Unit tests w/ clang
    runs-on: ubuntu-latest
    container: debian:bullseye-slim
    steps:
      - name: update apt + install CMake and g++
        run: apt-get update -q && apt-get install -y cmake clang++ git
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Let Cmake configure repo
        run: CXX=/usr/bin/clang cmake -S . -B build/
      - name: Build repo
        run: CXX=/usr/bin/clang cmake --build build/
      - name: Run Unit Tests
        run: cd build/tests && ctest
  

    
  

    