name: Unit Tests
on:
  push:
    branch: main

jobs:
  unit-tests-gcc:
    name: Unit tests w/ g++
    runs-on: ubuntu-latest
    steps:
      - name: update apt + install CMake and g++
        run: sudo apt-get update -q && sudo apt-get install cmake g++
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Let Cmake repo
        run: cmake -S . -B build/
      - name: Build repo
        run: cmake --build build/
      - name: Run Unit Tests
        run: cd build/tests && ctest

    