name: Compilation test
on:
  push:
      branches: [main]

jobs:
  unit-tests-clang:
    name: Compile clang 19
    runs-on: ubuntu-latest
    container: debian:trixie-slim
    steps:
      - name: Update apt and install dependencies
        run: apt-get update && apt-get install -y cmake git clang++-19
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Let CMake configure repo
        run: CXX=/usr/bin/clang++-19 cmake -S . -B build/
      - name: Build repo
        run: CXX=/usr/bin/clang++-19 cmake --build build/ --parallel
      # - name: Run Unit Tests
      #   run: cd build/tests && ctest
